const express = require('express')
const { getLiveMatches, getTodayMatches, getMatchById, getMatchEvents, getMatchStats, getMatchLineups } = require('../Controllers/matchController')
const { register, login, googleAuth, getProtected } = require('../Controllers/authcontroller')
const middleware = require('../utils/middleware')
const { saveFcmToken } = require('../Controllers/fcmController')
const router = express.Router()

router.post('/register', register)
router.post('/login', login)
router.post('/login/google', googleAuth)
router.get('/protected',middleware, getProtected)
router.get('/live', getLiveMatches)
router.get('/today', getTodayMatches)
router.get('/match/:id', getMatchById)
router.get('/match/:id/events', getMatchEvents)
router.get('/match/:id/stats', getMatchStats)
router.get('/match/:id/lineups', getMatchLineups)
router.post('/save-fcm-token',middleware,saveFcmToken)
module.exports = router