const express = require('express')
const { getLiveMatches, getTodayMatches, getMatchById, getMatchEvents, getMatchStats, getMatchLineups } = require('../Controllers/matchController')
const router = express.Router()
router.get('/live', getLiveMatches)
router.get('/today', getTodayMatches)
router.get('/match/:id', getMatchById)
router.get('/match/:id/events', getMatchEvents)
router.get('/match/:id/stats', getMatchStats)
router.get('/match/:id/lineups', getMatchLineups)
module.exports = router