version: "3.8"

services:

  backend:
    image: zabin0007/football-hub-backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/config/serviceAccountKey.json:/app/config/serviceAccountKey.json
    env_file:
      - Backend/.env
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  frontend:
    image: zabin0007/football-hub-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend